# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Latest release
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm ci
    - name: Jison parser npm install
      working-directory: ./tools/jison
      run: npm ci
    - name: Jison parser npm install
      working-directory: ./tools/jison
      run: node generateParsers.js databricks generic
    - run: npm run webpack-npm
    - name: Package parser
      working-directory: ./npm_dist
      run: npm pack
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "master"
        prerelease: true
        title: "Latest Build"
        files: npm_dist/gethue-*.tgz
