name: Tagged release
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm ci
    - name: Jison parser npm install
      working-directory: ./tools/jison
      run: npm ci
    - name: Jison parser generate
      working-directory: ./tools/jison
      run: node generateParsers.js databricks generic
    - run: npm run webpack-npm
    - run: tar -cf gethue.tar.gz ./npm_dist/**
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: gethue.tar.gz
